/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view.gudang;

import com.example.interfaces.Inventory;
import com.example.model.Barang;
import com.example.model.Gudang;
import com.example.model.Petugas;
import com.example.model.Stok;
import com.example.model.Transaksi;
import com.example.model.Transfer;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riel
 */
public class Home extends javax.swing.JFrame {

    private Inventory remote = null;
    private Petugas petugas = null;
    private Gudang gudang = null;
    private ArrayList<Stok> listStok = null;
    private ArrayList<Transaksi> listTx = null;
    private ArrayList<Transfer> listTf = null;
    private ArrayList<Barang> listBarang = null;

    public Home(Inventory remote, Petugas petugas) throws RemoteException {
        initComponents();
        setLocationRelativeTo(null);
        this.remote = remote;
        this.petugas = petugas;

        gudang = remote.getGudangById(petugas.getGudang());
        namaGudangTxt.setText(gudang.getNama());
        namaPetugasTxt.setText(petugas.getNama());
        loadAllTableData();
    }

    private void loadAllTableData() throws RemoteException {
        loadStok();
        loadTransaksi();
        loadTransfer();
        loadBarang();
    }

    private void loadStok() throws RemoteException {
        listStok = remote.getStokGudang(gudang.getId());
        DefaultTableModel model = (DefaultTableModel) tabelStok.getModel();
        model.setRowCount(0);
        if (listStok != null) {
            listStok.forEach((Stok stok) -> {
                Object o[] = {
                    stok.getId(),
                    stok.getNama(),
                    stok.getJumlah()
                };
                model.addRow(o);
            });
        }
    }

    private void loadTransaksi() throws RemoteException {
        listTx = remote.getTransaksiGudang(gudang.getId());
        DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        model.setRowCount(0);
        if (listTx != null) {
            listTx.forEach((Transaksi tx) -> {
                Object o[] = {
                    tx.getId(),
                    tx.getIdBarang(),
                    tx.getJumlah(),
                    tx.getTanggal(),
                    tx.getIdPetugas()
                };
                model.addRow(o);
            });
        }
    }

    private void loadTransfer() throws RemoteException {
        listTf = remote.getTransferGudang(gudang.getId());
        DefaultTableModel model = (DefaultTableModel) tabelTransfer.getModel();
        model.setRowCount(0);
        if (listTf != null) {
            listTf.forEach((Transfer tf) -> {
                Object o[] = {
                    tf.getId(),
                    tf.getBarang(),
                    tf.getJumlah(),
                    tf.getTanggal(),
                    tf.getPetugas(),
                    tf.getStatus(),
                    tf.getTransaksiTujuan()
                };
                model.addRow(o);
            });
        }
        System.out.println(gudang.getId());
    }

    private void loadBarang() throws RemoteException {
        listBarang = remote.getAllBarang();
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        model.setRowCount(0);
        if (listBarang != null) {
            listBarang.forEach((Barang barang) -> {
                Object o[] = {
                    barang.getId(),
                    barang.getNama()
                };
                model.addRow(o);
            });
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisTxRG = new javax.swing.ButtonGroup();
        fTf = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        fTfDariTanggal = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fTfSampaiTanggal = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        fTfIdBarangField = new javax.swing.JTextField();
        fTfJumlahField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        fTfPetugasCB = new javax.swing.JComboBox<>();
        fTfTerapkanBtn = new javax.swing.JButton();
        fTfHapusFilterBtn = new javax.swing.JButton();
        fTfBatalBtn = new javax.swing.JButton();
        fTfGudangCB = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        tambahTx = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        tambahTxKeluarRB = new javax.swing.JRadioButton();
        tambahTxMasukRB = new javax.swing.JRadioButton();
        tfLabel = new javax.swing.JLabel();
        tambahTfGudangCB = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        tambahTxIdBarangField = new javax.swing.JTextField();
        tambahTxJumlahField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tambahTxBtn = new javax.swing.JButton();
        batalTambahTxBtn = new javax.swing.JButton();
        tambahTxTransferCheckBox = new javax.swing.JCheckBox();
        fTx = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        fTxDariTanggal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fTxSampaiTanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        fTxKeluarRB = new javax.swing.JRadioButton();
        fTxMasukRB = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        fTxIdBarangField = new javax.swing.JTextField();
        fTxJumlahField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fTxPetugasCB = new javax.swing.JComboBox<>();
        fTxTerapkanBtn = new javax.swing.JButton();
        fTxHapusFilterBtn = new javax.swing.JButton();
        fTxBatalBtn = new javax.swing.JButton();
        tambahBarang = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tambahIdBarangField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tambahNamaBarangField = new javax.swing.JTextField();
        tambahBarangBtn = new javax.swing.JButton();
        batalTambahBarangBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaPetugasTxt = new javax.swing.JLabel();
        namaGudangTxt = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelStok = new javax.swing.JTable();
        cariStokField = new javax.swing.JTextField();
        cariStokButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resetCariStokButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        filterTransaksiBtn = new javax.swing.JButton();
        tambahTransaksiBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTransfer = new javax.swing.JTable();
        filterTransferButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        cariBarangButton = new javax.swing.JButton();
        tambahBarangButton = new javax.swing.JButton();
        cariBarangField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resetCariBarangButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        fTf.setMinimumSize(new java.awt.Dimension(476, 306));

        jLabel20.setText("Tanggal");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("-");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Filter Transfer");

        jLabel24.setText("ID Barang");

        jLabel25.setText("Jumlah");

        jLabel26.setText("Petugas");

        fTfPetugasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Petugas --" }));

        fTfTerapkanBtn.setText("Terapkan");
        fTfTerapkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTfTerapkanBtnActionPerformed(evt);
            }
        });

        fTfHapusFilterBtn.setText("Hapus Filter");
        fTfHapusFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTfHapusFilterBtnActionPerformed(evt);
            }
        });

        fTfBatalBtn.setText("Batal");
        fTfBatalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTfBatalBtnActionPerformed(evt);
            }
        });

        fTfGudangCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Gudang --" }));

        jLabel28.setText("Asal");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fTfJumlahField)
                                    .addComponent(fTfIdBarangField)
                                    .addComponent(fTfGudangCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(fTfDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fTfSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fTfPetugasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fTfBatalBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fTfHapusFilterBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fTfTerapkanBtn))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(fTfGudangCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(fTfIdBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(fTfJumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fTfSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(fTfDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(fTfPetugasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTfTerapkanBtn)
                    .addComponent(fTfHapusFilterBtn)
                    .addComponent(fTfBatalBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fTfLayout = new javax.swing.GroupLayout(fTf.getContentPane());
        fTf.getContentPane().setLayout(fTfLayout);
        fTfLayout.setHorizontalGroup(
            fTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fTfLayout.setVerticalGroup(
            fTfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tambahTx.setMinimumSize(new java.awt.Dimension(417, 295));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tambah Transaksi");

        jenisTxRG.add(tambahTxKeluarRB);
        tambahTxKeluarRB.setText("Keluar");
        tambahTxKeluarRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTxKeluarRBActionPerformed(evt);
            }
        });

        jenisTxRG.add(tambahTxMasukRB);
        tambahTxMasukRB.setText("Masuk");
        tambahTxMasukRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTxMasukRBActionPerformed(evt);
            }
        });

        tfLabel.setText("Tujuan");

        tambahTfGudangCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Gudang --" }));

        jLabel18.setText("ID Barang");

        jLabel19.setText("Jumlah");

        tambahTxBtn.setText("Tambah");
        tambahTxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTxBtnActionPerformed(evt);
            }
        });

        batalTambahTxBtn.setText("Batal");
        batalTambahTxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalTambahTxBtnActionPerformed(evt);
            }
        });

        tambahTxTransferCheckBox.setText("Transfer");
        tambahTxTransferCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTxTransferCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(tambahTxTransferCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(tambahTxKeluarRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(tambahTxMasukRB))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(tfLabel)
                                        .addGap(27, 27, 27)
                                        .addComponent(tambahTfGudangCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tambahTxIdBarangField)
                                    .addComponent(tambahTxJumlahField)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(batalTambahTxBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(tambahTxBtn)))))
                        .addGap(20, 20, 20))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahTxTransferCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahTxKeluarRB)
                    .addComponent(tambahTxMasukRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLabel)
                    .addComponent(tambahTfGudangCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tambahTxIdBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tambahTxJumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahTxBtn)
                    .addComponent(batalTambahTxBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahTxLayout = new javax.swing.GroupLayout(tambahTx.getContentPane());
        tambahTx.getContentPane().setLayout(tambahTxLayout);
        tambahTxLayout.setHorizontalGroup(
            tambahTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahTxLayout.setVerticalGroup(
            tambahTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fTx.setMinimumSize(new java.awt.Dimension(476, 314));

        jLabel8.setText("Tanggal");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Filter Transaksi");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Transfer");

        jenisTxRG.add(fTxKeluarRB);
        fTxKeluarRB.setText("Keluar");

        jenisTxRG.add(fTxMasukRB);
        fTxMasukRB.setText("Masuk");

        jLabel12.setText("ID Barang");

        jLabel13.setText("Jumlah");

        jLabel14.setText("Petugas");

        fTxPetugasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Petugas --" }));

        fTxTerapkanBtn.setText("Terapkan");
        fTxTerapkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxTerapkanBtnActionPerformed(evt);
            }
        });

        fTxHapusFilterBtn.setText("Hapus Filter");
        fTxHapusFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxHapusFilterBtnActionPerformed(evt);
            }
        });

        fTxBatalBtn.setText("Batal");
        fTxBatalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxBatalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fTxJumlahField)
                                    .addComponent(fTxIdBarangField)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(fTxDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fTxSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fTxPetugasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fTxBatalBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fTxHapusFilterBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fTxTerapkanBtn)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fTxKeluarRB)
                                .addGap(18, 18, 18)
                                .addComponent(fTxMasukRB))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTxKeluarRB)
                    .addComponent(fTxMasukRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fTxIdBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fTxJumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fTxSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(fTxDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fTxPetugasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTxTerapkanBtn)
                    .addComponent(fTxHapusFilterBtn)
                    .addComponent(fTxBatalBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fTxLayout = new javax.swing.GroupLayout(fTx.getContentPane());
        fTx.getContentPane().setLayout(fTxLayout);
        fTxLayout.setHorizontalGroup(
            fTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fTxLayout.setVerticalGroup(
            fTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tambahBarang.setMinimumSize(new java.awt.Dimension(367, 209));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tambah Barang");

        jLabel6.setText("ID");

        jLabel7.setText("Nama");

        tambahBarangBtn.setText("Tambah");
        tambahBarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangBtnActionPerformed(evt);
            }
        });

        batalTambahBarangBtn.setText("Batal");
        batalTambahBarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalTambahBarangBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(batalTambahBarangBtn)
                        .addGap(18, 18, 18)
                        .addComponent(tambahBarangBtn))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(30, 30, 30)
                            .addComponent(tambahNamaBarangField))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(56, 56, 56)
                            .addComponent(tambahIdBarangField))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tambahIdBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tambahNamaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBarangBtn)
                    .addComponent(batalTambahBarangBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang.getContentPane());
        tambahBarang.getContentPane().setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Inventory System");

        logoutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Petugas:");

        namaPetugasTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        namaPetugasTxt.setText("petugasTxt");

        namaGudangTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        namaGudangTxt.setText("gudangTxt");

        tabelStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelStok);

        cariStokField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        cariStokButton.setText("Cari");
        cariStokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariStokButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama barang:");

        resetCariStokButton.setText("Reset");
        resetCariStokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCariStokButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariStokField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariStokButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetCariStokButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cariStokField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cariStokButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetCariStokButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stok", jPanel3);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Barang", "Jumlah", "Tanggal", "Petugas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        filterTransaksiBtn.setText("Filter");
        filterTransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTransaksiBtnActionPerformed(evt);
            }
        });

        tambahTransaksiBtn.setText("Tambah");
        tambahTransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTransaksiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(983, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterTransaksiBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahTransaksiBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterTransaksiBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahTransaksiBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transaksi", jPanel4);

        tabelTransfer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Trans. Asal", "Id Barang", "Jumlah", "Tanggal", "Petugas", "Status", "Id Trans. Tujuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelTransfer);

        filterTransferButton.setText("Filter");
        filterTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTransferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterTransferButton)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterTransferButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transfer", jPanel5);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelBarang);

        cariBarangButton.setText("Cari");
        cariBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarangButtonActionPerformed(evt);
            }
        });

        tambahBarangButton.setText("Tambah");
        tambahBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangButtonActionPerformed(evt);
            }
        });

        cariBarangField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel5.setText("Nama barang:");

        resetCariBarangButton.setText("Reset");
        resetCariBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCariBarangButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBarangButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetCariBarangButton))
                    .addComponent(tambahBarangButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cariBarangField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cariBarangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetCariBarangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahBarangButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaGudangTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPetugasTxt)))
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaPetugasTxt)
                    .addComponent(namaGudangTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int answer = JOptionPane.showConfirmDialog(rootPane, "Apakah anda ingin logout?");
        System.out.println(answer);
        if (answer == 0) {
            try {
                new Login().setVisible(true);
                this.dispose();
            } catch (NotBoundException | RemoteException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void cariBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarangButtonActionPerformed
        if (listBarang != null) {
            DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
            model.setRowCount(0);
            listBarang.forEach((Barang b) -> {
                if (b.getNama().toLowerCase().contains(cariBarangField.getText().toLowerCase())) {
                    Object o[] = {
                        b.getId(),
                        b.getNama()
                    };
                    model.addRow(o);
                }
            });
        }
    }//GEN-LAST:event_cariBarangButtonActionPerformed

    private void resetCariBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCariBarangButtonActionPerformed
        cariBarangField.setText("");
        try {
            loadBarang();
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetCariBarangButtonActionPerformed

    private void resetCariStokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCariStokButtonActionPerformed
        cariStokField.setText("");
        try {
            loadStok();
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetCariStokButtonActionPerformed

    private void cariStokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariStokButtonActionPerformed
        if (listStok != null) {
            DefaultTableModel model = (DefaultTableModel) tabelStok.getModel();
            model.setRowCount(0);
            listStok.forEach((Stok s) -> {
                if (s.getNama().toLowerCase().contains(cariStokField.getText().toLowerCase())) {
                    Object o[] = {
                        s.getId(),
                        s.getNama(),
                        s.getJumlah()
                    };
                    model.addRow(o);
                }
            });
        }
    }//GEN-LAST:event_cariStokButtonActionPerformed

    private void tambahBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangButtonActionPerformed
        tambahBarang.setVisible(true);
        tambahBarang.setLocationRelativeTo(this);
    }//GEN-LAST:event_tambahBarangButtonActionPerformed

    private void filterTransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTransaksiBtnActionPerformed
        fTx.setVisible(true);
        fTx.setLocationRelativeTo(this);
    }//GEN-LAST:event_filterTransaksiBtnActionPerformed

    private void filterTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTransferButtonActionPerformed
        fTf.setVisible(true);
        fTf.setLocationRelativeTo(this);
    }//GEN-LAST:event_filterTransferButtonActionPerformed

    private void batalTambahBarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalTambahBarangBtnActionPerformed
        tambahBarang.dispose();
    }//GEN-LAST:event_batalTambahBarangBtnActionPerformed

    private void fTxBatalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxBatalBtnActionPerformed
        fTx.dispose();
    }//GEN-LAST:event_fTxBatalBtnActionPerformed

    private void batalTambahTxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalTambahTxBtnActionPerformed
        tambahTx.dispose();
    }//GEN-LAST:event_batalTambahTxBtnActionPerformed

    private void fTfBatalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTfBatalBtnActionPerformed
        fTf.dispose();
    }//GEN-LAST:event_fTfBatalBtnActionPerformed

    private void tambahTxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTxBtnActionPerformed
        if (tambahTxIdBarangField.getText().isEmpty()
                || tambahTxJumlahField.getText().isEmpty()
                || (tambahTxTransferCheckBox.isSelected()
                && !(tambahTxKeluarRB.isSelected() || tambahTxMasukRB.isSelected()))) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Harap mengisi semua data.",
                    "Perhatian",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }
        if(tambahTxMasukRB.isSelected()) {
            System.out.println("masuk");
            
        }
    }//GEN-LAST:event_tambahTxBtnActionPerformed

    private void fTfHapusFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTfHapusFilterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTfHapusFilterBtnActionPerformed

    private void fTfTerapkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTfTerapkanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTfTerapkanBtnActionPerformed

    private void fTxHapusFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxHapusFilterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTxHapusFilterBtnActionPerformed

    private void fTxTerapkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxTerapkanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTxTerapkanBtnActionPerformed

    private void tambahBarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangBtnActionPerformed
        if (tambahIdBarangField.getText().isEmpty()
                || tambahNamaBarangField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Harap mengisi semua data.",
                    "Perhatian",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        int answer = JOptionPane.showConfirmDialog(rootPane, "Simpan barang baru?");
        if (answer == 0) {
            Barang b = new Barang(
                    tambahIdBarangField.getText(),
                    tambahNamaBarangField.getText()
            );
            try {
                int response = remote.insertBarang(b);
                switch (response) {
                    case 1:
                        JOptionPane.showMessageDialog(rootPane, "Berhasil disimpan");
                        loadBarang();
                        tambahBarang.dispose();
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(rootPane, "ID gudang " + tambahIdBarangField.getText() + " sudah dipakai.", "Error - Duplikat ID", JOptionPane.ERROR_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Gagal disimpan");
                        break;
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tambahBarangBtnActionPerformed

    private void tambahTransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTransaksiBtnActionPerformed
        tambahTx.setVisible(true);
        tambahTx.setLocationRelativeTo(this);
        Enumeration<AbstractButton> enumeration = jenisTxRG.getElements();
        while (enumeration.hasMoreElements()) {
            enumeration.nextElement().setEnabled(false);
        }
        jenisTxRG.clearSelection();
        tambahTfGudangCB.enable(false);
    }//GEN-LAST:event_tambahTransaksiBtnActionPerformed

    private void tambahTxTransferCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTxTransferCheckBoxActionPerformed
        if (!tambahTxTransferCheckBox.isSelected()) {
            Enumeration<AbstractButton> enumeration = jenisTxRG.getElements();
            while (enumeration.hasMoreElements()) {
                enumeration.nextElement().setEnabled(false);
            }
            jenisTxRG.clearSelection();
            tambahTfGudangCB.enable(false);
            System.out.println("disabled");
        } else {
            Enumeration<AbstractButton> enumeration = jenisTxRG.getElements();
            while (enumeration.hasMoreElements()) {
                enumeration.nextElement().setEnabled(true);
            }
            tambahTfGudangCB.enable(true);
            System.out.println("enabled");
        }
    }//GEN-LAST:event_tambahTxTransferCheckBoxActionPerformed

    private void tambahTxKeluarRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTxKeluarRBActionPerformed
        tfLabel.setText("Tujuan");
    }//GEN-LAST:event_tambahTxKeluarRBActionPerformed

    private void tambahTxMasukRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTxMasukRBActionPerformed
        tfLabel.setText("Asal");
    }//GEN-LAST:event_tambahTxMasukRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Petugas petugas = new Petugas("pd", "Petugas D", null, null, "ga");
                Inventory remote = null;
                Registry registry;
                try {
                    registry = LocateRegistry.getRegistry(5000);
                    remote = (Inventory) registry
                            .lookup("inventory");
                    new Home(remote, petugas).setVisible(true);
                } catch (RemoteException | NotBoundException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalTambahBarangBtn;
    private javax.swing.JButton batalTambahTxBtn;
    private javax.swing.JButton cariBarangButton;
    private javax.swing.JTextField cariBarangField;
    private javax.swing.JButton cariStokButton;
    private javax.swing.JTextField cariStokField;
    private javax.swing.JDialog fTf;
    private javax.swing.JButton fTfBatalBtn;
    private com.toedter.calendar.JDateChooser fTfDariTanggal;
    private javax.swing.JComboBox<String> fTfGudangCB;
    private javax.swing.JButton fTfHapusFilterBtn;
    private javax.swing.JTextField fTfIdBarangField;
    private javax.swing.JTextField fTfJumlahField;
    private javax.swing.JComboBox<String> fTfPetugasCB;
    private com.toedter.calendar.JDateChooser fTfSampaiTanggal;
    private javax.swing.JButton fTfTerapkanBtn;
    private javax.swing.JDialog fTx;
    private javax.swing.JButton fTxBatalBtn;
    private com.toedter.calendar.JDateChooser fTxDariTanggal;
    private javax.swing.JButton fTxHapusFilterBtn;
    private javax.swing.JTextField fTxIdBarangField;
    private javax.swing.JTextField fTxJumlahField;
    private javax.swing.JRadioButton fTxKeluarRB;
    private javax.swing.JRadioButton fTxMasukRB;
    private javax.swing.JComboBox<String> fTxPetugasCB;
    private com.toedter.calendar.JDateChooser fTxSampaiTanggal;
    private javax.swing.JButton fTxTerapkanBtn;
    private javax.swing.JButton filterTransaksiBtn;
    private javax.swing.JButton filterTransferButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.ButtonGroup jenisTxRG;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel namaGudangTxt;
    private javax.swing.JLabel namaPetugasTxt;
    private javax.swing.JButton resetCariBarangButton;
    private javax.swing.JButton resetCariStokButton;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelStok;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTable tabelTransfer;
    private javax.swing.JDialog tambahBarang;
    private javax.swing.JButton tambahBarangBtn;
    private javax.swing.JButton tambahBarangButton;
    private javax.swing.JTextField tambahIdBarangField;
    private javax.swing.JTextField tambahNamaBarangField;
    private javax.swing.JComboBox<String> tambahTfGudangCB;
    private javax.swing.JButton tambahTransaksiBtn;
    private javax.swing.JDialog tambahTx;
    private javax.swing.JButton tambahTxBtn;
    private javax.swing.JTextField tambahTxIdBarangField;
    private javax.swing.JTextField tambahTxJumlahField;
    private javax.swing.JRadioButton tambahTxKeluarRB;
    private javax.swing.JRadioButton tambahTxMasukRB;
    private javax.swing.JCheckBox tambahTxTransferCheckBox;
    private javax.swing.JLabel tfLabel;
    // End of variables declaration//GEN-END:variables
}
